# Generated by Django 4.2.6 on 2023-10-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geosync',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geosync',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued ⌛'), ('in_progress', 'In Flight ✈️'), ('success', 'Success ✅'), ('error', 'Its On Fire 🔥')], default='queued', max_length=255),
        ),
    ]
