# Generated by Django 4.2.6 on 2023-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigint', '0002_geosync_expires_alter_geosync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessplan',
            name='throttle_rate',
            field=models.CharField(default='120/m', max_length=255),
        ),
    ]
