# Generated by Django 4.2.6 on 2023-10-16 03:26

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigint', '0003_alter_accessplan_throttle_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geosync',
            name='asn_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='geosync',
            name='city_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='geosync',
            name='country_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=''),
        ),
    ]
