# Generated by Django 4.2.6 on 2023-10-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigint', '0006_lookuprequest_error_info_alter_accessplan_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressresult',
            name='lookup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='sigint.lookuprequest'),
        ),
        migrations.AlterField(
            model_name='addressresult',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Postal Code'),
        ),
    ]
