# Generated by Django 4.2.6 on 2023-10-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigint', '0008_alter_addressresult_ip_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressresult',
            name='continent_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
